// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCohhTTGYGZZxqLAWHV-WT_vH6rn7ROBb8',
    appId: '1:439076440162:web:f4db7b03a4aa9156f2693b',
    messagingSenderId: '439076440162',
    projectId: 'kigali-directory-app-d381d',
    authDomain: 'kigali-directory-app-d381d.firebaseapp.com',
    storageBucket: 'kigali-directory-app-d381d.firebasestorage.app',
    measurementId: 'G-PLNPXLP6TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDabcMo58p9JwDGt8kwQwDQgM7Gc3T7PRc',
    appId: '1:439076440162:android:a2e58280351f8bdff2693b',
    messagingSenderId: '439076440162',
    projectId: 'kigali-directory-app-d381d',
    storageBucket: 'kigali-directory-app-d381d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGziYDtGilDlgAp5p4rR5y-WCXyaek5tw',
    appId: '1:439076440162:ios:3565ca74b4e74ed6f2693b',
    messagingSenderId: '439076440162',
    projectId: 'kigali-directory-app-d381d',
    storageBucket: 'kigali-directory-app-d381d.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGziYDtGilDlgAp5p4rR5y-WCXyaek5tw',
    appId: '1:439076440162:ios:3565ca74b4e74ed6f2693b',
    messagingSenderId: '439076440162',
    projectId: 'kigali-directory-app-d381d',
    storageBucket: 'kigali-directory-app-d381d.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCohhTTGYGZZxqLAWHV-WT_vH6rn7ROBb8',
    appId: '1:439076440162:web:ca82356f03a4f254f2693b',
    messagingSenderId: '439076440162',
    projectId: 'kigali-directory-app-d381d',
    authDomain: 'kigali-directory-app-d381d.firebaseapp.com',
    storageBucket: 'kigali-directory-app-d381d.firebasestorage.app',
    measurementId: 'G-K6J2GCSVR8',
  );
}
